version : '3.6'
services :
  app-iudigital :
    build :
      context: .
    ports :
      - "8084:8084"
    environment :
      DATABASE_URL : jdbc:mysql://basedatos:3306/iudigital?createDatabaseIfNotExist=true
      DATABASE_USERNAME : iudigital
      DATABASE_PASSWORD : Cambiar123@
    restart: always
    networks :
      - iudigital
    depends_on :
      - basedatos

  basedatos :
    image : mysql:latest
    environment :
      MYSQL_ROOT_PASSWORD : Cambiar123@
      MYSQL_DATABASE : iudigital
      MYSQL_USER : iudigital
      MYSQL_PASSWORD : Cambiar123@
    ports :
      - "3306:3306"
    volumes :
      - db_data:/var/lib/mysql
    networks :
      - iudigital

networks :
  iudigital :

volumes :
  db_data :