server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:
  application:
    name: API Iudigital
# conexión a base de datos
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true