server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:
  application:
    name: API Iudigital
  # conexión a base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/iudigital?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true